name: empire
description: A simple yet powerful state management library for [Flutter](https://flutter.dev/).
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:    
  flutter:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.1

flutter:
